#!/usr/bin/env python3
"""Generate src/game/td_template_table.h from the original Tiberian Dawn source.

Template IDs in TD .bin maps are indices into the TemplateType enum
(reference/CnC_Tiberian_Dawn/DEFINES.H). The ID -> art filename + theater
availability mapping comes from the TemplateTypeClass constructor calls in
CDATA.CPP (multi-line: enum, theater flags, "ART", ...). Cross-checked against
OpenRA mods/cnc/tilesets/{desert,temperate,winter}.yaml.

TD theaters: DESERT=0, JUNGLE=1, TEMPERATE=2, WINTER=3 (JUNGLE unused/shipped).

Usage: python tools/gen_td_template_table.py
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFINES_H = ROOT / "reference/CnC_Tiberian_Dawn/DEFINES.H"
CDATA_CPP = ROOT / "reference/CnC_Tiberian_Dawn/CDATA.CPP"
OUT_H = ROOT / "src/game/td_template_table.h"

THEATER_BITS = {
    "THEATERF_DESERT": 1, "THEATERF_JUNGLE": 2,
    "THEATERF_TEMPERATE": 4, "THEATERF_WINTER": 8,
}


def parse_enum(text):
    """Return TemplateType enum names in declaration order (IDs 0..N-1)."""
    m = re.search(r"typedef enum TemplateType \{(.*?)\} TemplateType;", text, re.S)
    if not m:
        sys.exit("TemplateType enum not found in DEFINES.H")
    names = []
    for line in m.group(1).splitlines():
        line = line.split("//")[0].strip()
        if not line or line.startswith("#"):
            continue
        name = line.rstrip(",").strip()
        if name == "TEMPLATE_COUNT":
            break
        if "=" in name:  # TEMPLATE_NONE=255, TEMPLATE_FIRST=0
            continue
        names.append(name)
    return names


def parse_constructors(text):
    """Map TEMPLATE_* enum name -> (art filename, theater mask)."""
    pat = re.compile(
        r"TemplateTypeClass\s+const\s+\w+\s*\(\s*"
        r"(TEMPLATE_\w+)\s*,\s*"    # enum
        r"([A-Z_|\s]+?)\s*,\s*"     # theater flags (may span lines)
        r'"([^"]+)"',               # art name
        re.S,
    )
    table = {}
    for enum_name, flags, art in pat.findall(text):
        mask = 0
        for f in flags.split("|"):
            f = f.strip()
            if f in THEATER_BITS:
                mask |= THEATER_BITS[f]
        if enum_name in table and table[enum_name] != (art, mask):
            # Empty/Clear both map to TEMPLATE_CLEAR1 with identical data.
            sys.exit(f"conflicting definitions for {enum_name}: "
                     f"{table[enum_name]} vs {(art, mask)}")
        table[enum_name] = (art, mask)
    return table


def main():
    enum_names = parse_enum(DEFINES_H.read_text(errors="replace"))
    ctors = parse_constructors(CDATA_CPP.read_text(errors="replace"))

    missing = [n for n in enum_names if n not in ctors]
    if missing:
        print(f"warning: {len(missing)} enum entries with no constructor "
              f"(emitting as clear): {missing}", file=sys.stderr)

    lines = [
        "// Generated by tools/gen_td_template_table.py -- do not edit.",
        "// Source: reference/CnC_Tiberian_Dawn/{DEFINES.H,CDATA.CPP}.",
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        "namespace game {",
        "",
        "enum TdTheaterFlags : uint8_t {",
        "    kTdTheaterDesert = 1,",
        "    kTdTheaterJungle = 2,",
        "    kTdTheaterTemperate = 4,",
        "    kTdTheaterWinter = 8,",
        "};",
        "",
        "struct TdTemplateInfo {",
        "    const char* name;      // art base name; add theater extension (.des/.tem/.win)",
        "    uint8_t theaters;      // TdTheaterFlags mask",
        "};",
        "",
        "// Indexed by the u8 template ID stored in TD .bin map cells.",
        "inline constexpr TdTemplateInfo kTdTemplateTable[] = {",
    ]
    for i, n in enumerate(enum_names):
        art, mask = ctors.get(n, ("", 0))
        lines.append(f'    {{"{art.lower()}", {mask}}},  // {i} {n}')
    lines += [
        "};",
        "",
        "inline constexpr uint16_t kTdTemplateCount = "
        "sizeof(kTdTemplateTable) / sizeof(kTdTemplateTable[0]);",
        "",
        "}  // namespace game",
        "",
    ]
    OUT_H.parent.mkdir(parents=True, exist_ok=True)
    OUT_H.write_text("\n".join(lines), newline="\n")
    print(f"wrote {OUT_H.relative_to(ROOT)}: {len(enum_names)} templates, "
          f"{len(ctors)} constructors")


if __name__ == "__main__":
    main()
