#!/usr/bin/env python3
"""Generate src/game/template_table.h from the original Red Alert source.

Template IDs in RA map files are indices into the TemplateType enum
(reference/CnC_Red_Alert/CODE/DEFINES.H). The ID -> art filename + theater
availability mapping comes from the TemplateTypeClass constructor calls in
CDATA.CPP. FIXIT_ANTS is treated as defined (retail/Aftermath behavior), so
TEMPLATE_HILL01 is included.

Usage: python tools/gen_template_table.py
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFINES_H = ROOT / "reference/CnC_Red_Alert/CODE/DEFINES.H"
CDATA_CPP = ROOT / "reference/CnC_Red_Alert/CODE/CDATA.CPP"
OUT_H = ROOT / "src/game/template_table.h"

THEATER_BITS = {"THEATERF_TEMPERATE": 1, "THEATERF_SNOW": 2, "THEATERF_INTERIOR": 4}


def parse_enum(text):
    """Return TemplateType enum names in declaration order (IDs 0..N-1)."""
    m = re.search(r"typedef enum TemplateType \{(.*?)\} TemplateType;", text, re.S)
    if not m:
        sys.exit("TemplateType enum not found in DEFINES.H")
    names = []
    for line in m.group(1).splitlines():
        line = line.split("//")[0].strip()
        # FIXIT_ANTS is defined in retail builds; keep everything, only skip
        # directives themselves.
        if not line or line.startswith("#"):
            continue
        name = line.rstrip(",").strip()
        if "=" in name:  # TEMPLATE_NONE=65535, TEMPLATE_FIRST=0
            continue
        if name == "TEMPLATE_COUNT":
            break
        names.append(name)
    return names


def parse_constructors(text):
    """Map TEMPLATE_* enum name -> (art filename, theater mask)."""
    pat = re.compile(
        r"TemplateTypeClass\s+const\s+\w+\s*\(\s*"
        r"(TEMPLATE_\w+)\s*,\s*"  # enum
        r"([A-Z_|\s]+?)\s*,\s*"   # theater flags
        r'"([^"]+)"',              # art name
        re.S,
    )
    table = {}
    for enum_name, flags, art in pat.findall(text):
        mask = 0
        for f in flags.split("|"):
            mask |= THEATER_BITS[f.strip()]
        if enum_name in table and table[enum_name] != (art, mask):
            sys.exit(f"conflicting definitions for {enum_name}")
        table[enum_name] = (art, mask)
    return table


def main():
    enum_names = parse_enum(DEFINES_H.read_text(errors="replace"))
    ctors = parse_constructors(CDATA_CPP.read_text(errors="replace"))

    missing = [n for n in enum_names if n not in ctors]
    if missing:
        sys.exit(f"enum entries with no constructor: {missing}")
    extra = set(ctors) - set(enum_names)
    if extra:
        sys.exit(f"constructors with no enum entry: {sorted(extra)}")

    lines = [
        "// Generated by tools/gen_template_table.py -- do not edit.",
        "// Source: reference/CnC_Red_Alert/CODE/{DEFINES.H,CDATA.CPP} (FIXIT_ANTS on).",
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        "namespace game {",
        "",
        "enum TheaterFlags : uint8_t {",
        "    kTheaterTemperate = 1,",
        "    kTheaterSnow = 2,",
        "    kTheaterInterior = 4,",
        "};",
        "",
        "struct TemplateInfo {",
        "    const char* name;      // art base name; add theater extension (.tem/.sno/.int)",
        "    uint8_t theaters;      // TheaterFlags mask",
        "};",
        "",
        "// Indexed by the u16 template ID stored in map MapPack cells.",
        "inline constexpr TemplateInfo kTemplateTable[] = {",
    ]
    for i, n in enumerate(enum_names):
        art, mask = ctors[n]
        lines.append(f'    {{"{art.lower()}", {mask}}},  // {i} {n}')
    lines += [
        "};",
        "",
        "inline constexpr uint16_t kTemplateCount = "
        "sizeof(kTemplateTable) / sizeof(kTemplateTable[0]);",
        "",
        "}  // namespace game",
        "",
    ]
    OUT_H.parent.mkdir(parents=True, exist_ok=True)
    OUT_H.write_text("\n".join(lines), newline="\n")
    print(f"wrote {OUT_H.relative_to(ROOT)}: {len(enum_names)} templates")


if __name__ == "__main__":
    main()
