#!/usr/bin/env python3
"""Generate src/game/td_template_table.h from the original Tiberian Dawn source.

Template IDs in TD .bin maps are indices into the TemplateType enum
(reference/CnC_Tiberian_Dawn/DEFINES.H). The ID -> art filename + theater
availability mapping comes from the TemplateTypeClass constructor calls in
CDATA.CPP (multi-line: enum, theater flags, "ART", ...). Cross-checked against
OpenRA mods/cnc/tilesets/{desert,temperate,winter}.yaml.

TD theaters: DESERT=0, JUNGLE=1, TEMPERATE=2, WINTER=3 (JUNGLE unused/shipped).

Usage: python tools/gen_td_template_table.py
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFINES_H = ROOT / "reference/CnC_Tiberian_Dawn/DEFINES.H"
CDATA_CPP = ROOT / "reference/CnC_Tiberian_Dawn/CDATA.CPP"
OUT_H = ROOT / "src/game/td_template_table.h"

THEATER_BITS = {
    "THEATERF_DESERT": 1, "THEATERF_JUNGLE": 2,
    "THEATERF_TEMPERATE": 4, "THEATERF_WINTER": 8,
}

# TD LandType (DEFINES.H) -> our game::Land value. The first seven entries of
# both enums coincide (Clear/Road/Water/Rock/Wall/{Tiberium=Ore}/Beach), so the
# raw index would do; the explicit map documents the correspondence and guards
# against future divergence.
LAND_TO_GAME = {
    "LAND_CLEAR": 0, "LAND_ROAD": 1, "LAND_WATER": 2, "LAND_ROCK": 3,
    "LAND_WALL": 4, "LAND_TIBERIUM": 5, "LAND_BEACH": 6,
}


def parse_enum(text):
    """Return TemplateType enum names in declaration order (IDs 0..N-1)."""
    m = re.search(r"typedef enum TemplateType \{(.*?)\} TemplateType;", text, re.S)
    if not m:
        sys.exit("TemplateType enum not found in DEFINES.H")
    names = []
    for line in m.group(1).splitlines():
        line = line.split("//")[0].strip()
        if not line or line.startswith("#"):
            continue
        name = line.rstrip(",").strip()
        if name == "TEMPLATE_COUNT":
            break
        if "=" in name:  # TEMPLATE_NONE=255, TEMPLATE_FIRST=0
            continue
        names.append(name)
    return names


def parse_slopes(text):
    """Map _slope* array name -> list of icon indices (drops the -1 sentinel)."""
    pat = re.compile(r"static\s+char\s+const\s+(_slope\w+)\s*\[\]\s*=\s*\{([^}]*)\}")
    slopes = {}
    for name, body in pat.findall(text):
        nums = [int(x) for x in body.split(",") if x.strip() not in ("", "-1")]
        slopes[name] = nums
    return slopes


def parse_constructors(text):
    """Map TEMPLATE_* enum name -> (art, theater mask, land, altLand, altSlope,
    width, height).

    Constructor arg order (TYPE.H): iconset, theater, ininame, fullname, land,
    width, height, altland, alticons. `width`/`height` are the template's icon
    footprint (cells). `alticons` is NULL or a cast pointer to a _slope*
    exception list whose icons take `altland` instead of `land`.
    """
    pat = re.compile(
        r"TemplateTypeClass\s+const\s+\w+\s*\(\s*"
        r"(TEMPLATE_\w+)\s*,\s*"     # 1 enum
        r"([A-Z0-9_|\s]+?)\s*,\s*"   # 2 theater flags (may span lines)
        r'"([^"]+)"\s*,\s*'          # 3 art name
        r"\w+\s*,\s*"                #   fullname (TXT_*)
        r"(LAND_\w+)\s*,\s*"         # 4 land
        r"(\d+)\s*,\s*(\d+)\s*,\s*"  # 5,6 width, height (icons)
        r"(LAND_\w+)\s*,\s*"         # 7 altland
        r"([^;]+?)\s*\)\s*;",        # 8 alticons expression
        re.S,
    )
    table = {}
    for enum_name, flags, art, land, width, height, altland, alticons in pat.findall(text):
        mask = 0
        for f in flags.split("|"):
            f = f.strip()
            if f in THEATER_BITS:
                mask |= THEATER_BITS[f]
        m = re.search(r"_slope\w+", alticons)
        alt_slope = m.group(0) if m else None
        entry = (art, mask, LAND_TO_GAME[land], LAND_TO_GAME[altland], alt_slope,
                 int(width), int(height))
        if enum_name in table and table[enum_name] != entry:
            # Empty/Clear both map to TEMPLATE_CLEAR1 with identical data.
            sys.exit(f"conflicting definitions for {enum_name}: "
                     f"{table[enum_name]} vs {entry}")
        table[enum_name] = entry
    return table


def main():
    enum_names = parse_enum(DEFINES_H.read_text(errors="replace"))
    cdata = CDATA_CPP.read_text(errors="replace")
    ctors = parse_constructors(cdata)
    slopes = parse_slopes(cdata)

    missing = [n for n in enum_names if n not in ctors]
    if missing:
        print(f"warning: {len(missing)} enum entries with no constructor "
              f"(emitting as clear): {missing}", file=sys.stderr)

    # Emit only the exception lists actually referenced, in first-use order.
    used_slopes = []
    for n in enum_names:
        alt_slope = ctors.get(n, ("", 0, 0, 0, None, 1, 1))[4]
        if alt_slope and alt_slope not in used_slopes:
            used_slopes.append(alt_slope)

    lines = [
        "// Generated by tools/gen_td_template_table.py -- do not edit.",
        "// Source: reference/CnC_Tiberian_Dawn/{DEFINES.H,CDATA.CPP}.",
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        "namespace game {",
        "",
        "enum TdTheaterFlags : uint8_t {",
        "    kTdTheaterDesert = 1,",
        "    kTdTheaterJungle = 2,",
        "    kTdTheaterTemperate = 4,",
        "    kTdTheaterWinter = 8,",
        "};",
        "",
        "struct TdTemplateInfo {",
        "    const char* name;         // art base name; add theater ext (.des/.tem/.win)",
        "    uint8_t theaters;         // TdTheaterFlags mask",
        "    uint8_t land;             // default game::Land value for the template's icons",
        "    uint8_t altLand;          // game::Land value for the altIcons exception list",
        "    const int8_t* altIcons;   // -1-terminated icon indices taking altLand; null=none",
        "    uint8_t width;            // template footprint in cells (icons per row)",
        "    uint8_t height;           // template footprint in cells (rows)",
        "};",
        "",
        "// Per-template icon exception lists (TemplateTypeClass AltIcons); the listed",
        "// icons take altLand, all others take land (CELL.CPP Cell_Class::Land_Type).",
    ]
    for name in used_slopes:
        nums = ", ".join(str(x) for x in slopes[name])
        lines.append(f"inline constexpr int8_t kTdAlt{name}[] = {{{nums}, -1}};")
    lines += [
        "",
        "// Indexed by the u8 template ID stored in TD .bin map cells.",
        "inline constexpr TdTemplateInfo kTdTemplateTable[] = {",
    ]
    for i, n in enumerate(enum_names):
        art, mask, land, altland, alt_slope, width, height = ctors.get(
            n, ("", 0, 0, 0, None, 1, 1))
        alt_ptr = f"kTdAlt{alt_slope}" if alt_slope else "nullptr"
        lines.append(
            f'    {{"{art.lower()}", {mask}, {land}, {altland}, {alt_ptr}, '
            f'{width}, {height}}},'
            f'  // {i} {n}')
    lines += [
        "};",
        "",
        "inline constexpr uint16_t kTdTemplateCount = "
        "sizeof(kTdTemplateTable) / sizeof(kTdTemplateTable[0]);",
        "",
        "}  // namespace game",
        "",
    ]
    OUT_H.parent.mkdir(parents=True, exist_ok=True)
    OUT_H.write_text("\n".join(lines), newline="\n")
    print(f"wrote {OUT_H.relative_to(ROOT)}: {len(enum_names)} templates, "
          f"{len(ctors)} constructors")


if __name__ == "__main__":
    main()
